# Generated by Django 5.0.4 on 2024-04-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_country_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
